import typing
from ._decorators import cached_class_property as cached_class_property
from .enums import DateTimeTo as DateTimeTo, EnvKeyStrategy as EnvKeyStrategy, EnvPrecedence as EnvPrecedence, KeyAction as KeyAction, KeyCase as KeyCase
from .models import Condition as Condition
from typing import Callable, ClassVar as _ClassVar
from ._path_util import EnvFilePaths, SecretsDirs
from ._bases_meta import ALLOWED_MODES, HookFn, PreDecoder

TYPE_CHECKING: bool
TAG: str

# Create a generic variable that can be 'AbstractMeta', or any subclass.
# Full word as `M` is already defined in another module
META_ = typing.TypeVar('META_', AbstractMeta, AbstractEnvMeta)
# Use `type` here explicitly, because we will never have an `META_` object.
META = type[META_]

# Create a generic variable that can be 'AbstractMeta', or any subclass.
# Full word as `M` is already defined in another module
ENV_META_ = typing.TypeVar('ENV_META_', bound='AbstractEnvMeta')
# Use `type` here explicitly, because we will never have an `META_` object.
ENV_META = type[ENV_META_]

TypeToHook = typing.Mapping[type, tuple[ALLOWED_MODES, HookFn] | HookFn | None]

class ABCOrAndMeta(type):
    @classmethod
    def __or__(cls: META, other: META) -> META: ...
    @classmethod
    def __and__(cls: META, other: META) -> META: ...

class BaseMeta:
    __special_attrs__: _ClassVar[frozenset] = ...
    __is_inner_meta__: _ClassVar[bool] = ...
    recursive: _ClassVar[bool] = ...
    tag: _ClassVar[None] = ...
    tag_key: _ClassVar[str] = ...
    auto_assign_tags: _ClassVar[bool] = ...
    skip_defaults: _ClassVar[bool] = ...
    skip_if: _ClassVar[None] = ...
    skip_defaults_if: _ClassVar[None] = ...
    debug: _ClassVar[bool] = ...
    type_to_load_hook: _ClassVar[TypeToHook | None] = ...
    type_to_dump_hook: _ClassVar[TypeToHook | None] = ...
    pre_decoder: _ClassVar[None] = ...
    dump_case: _ClassVar[None] = ...
    field_to_alias_dump: _ClassVar[typing.Mapping[str, str | typing.Sequence[str]] | None] = ...
    unsafe_parse_dataclass_in_union: _ClassVar[bool] = ...
    dump_date_time_as: _ClassVar[None] = ...
    assume_naive_datetime_tz: _ClassVar[None] = ...
    namedtuple_as_dict: _ClassVar[None] = ...
    coerce_none_to_empty_str: _ClassVar[None] = ...
    leaf_handling: _ClassVar[None] = ...
    all_fields: _ClassVar[frozenset] = ...
    fields_to_merge: _ClassVar[frozenset] = ...

class AbstractMeta(BaseMeta):
    __special_attrs__: _ClassVar[frozenset] = ...
    __is_inner_meta__: _ClassVar[bool] = ...
    case: _ClassVar[None] = ...
    load_case: _ClassVar[None] = ...
    field_to_alias: _ClassVar[None] = ...
    field_to_alias_load: _ClassVar[typing.Mapping[str, str | typing.Sequence[str] | None]] = ...
    on_unknown_key: _ClassVar[None] = ...
    @classmethod
    def bind_to(cls, dataclass: type, create: bool = ..., is_default: bool = ...): ...

class AbstractEnvMeta(BaseMeta):
    __special_attrs__: _ClassVar[frozenset] = ...
    __is_inner_meta__: _ClassVar[bool] = ...
    env_file: _ClassVar[None] = ...
    env_prefix: _ClassVar[None] = ...
    secrets_dir: _ClassVar[None] = ...
    load_case: _ClassVar[None] = ...
    env_precedence: _ClassVar[None] = ...
    field_to_env_load: _ClassVar[None] = ...
    @classmethod
    def bind_to(cls, env_class: type, create: bool = ..., is_default: bool = ...): ...

class _BaseHookRegistry:
    @classmethod
    def __init_subclass__(cls): ...
    @classmethod
    def register_hook(cls, typ: type, func: Callable): ...
    @classmethod
    def get_hook(cls, typ: type) -> Callable | None: ...

class BaseLoadHook(_BaseHookRegistry):
    __HOOKS__: _ClassVar[dict] = ...

class BaseDumpHook(_BaseHookRegistry):
    __HOOKS__: _ClassVar[dict] = ...
