import dataclasses
from _typeshed import Incomplete

def _get_resolved_annotations(obj) -> dict: ...
def property_wizard(*args, **kwargs): ...
def _process_public_property(cls: type, public_f: str, val: property, annotations: dict, annotation_repls: dict): ...
def _process_underscored_property(cls: type, under_f: str, val: property, annotations: dict, annotation_repls: dict): ...
def _process_field(cls: type, cls_annotations: dict, field: str, field_val: dataclasses.Field) -> tuple: ...
def _default_from_annotation(cls: type, cls_annotations: dict, field: str) -> dataclasses.Field: ...
def _default_from_type(default_type: type) -> dataclasses.Field: ...
def _default_from_generic_type(cls: type, default_type: type, field: str = ...) -> dataclasses.Field: ...
def _default_from_typing_args(args: Incomplete): ...
def _wrapper(fset, fval: dataclasses.Field): ...
