import enum
import typing
from _typeshed import Incomplete
from .utils._string_case import to_camel_case as to_camel_case, to_lisp_case as to_lisp_case, to_pascal_case as to_pascal_case, to_snake_case as to_snake_case
from typing import ClassVar

class FuncWrapper:
    f: Incomplete
    def __init__(self, f: typing.Callable) -> None: ...
    def __call__(self, *args, **kwargs): ...

class KeyAction(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    IGNORE: ClassVar[KeyAction] = ...
    RAISE: ClassVar[KeyAction] = ...
    WARN: ClassVar[KeyAction] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class EnvKeyStrategy(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    ENV: ClassVar[EnvKeyStrategy] = ...
    FIELD_FIRST: ClassVar[EnvKeyStrategy] = ...
    STRICT: ClassVar[EnvKeyStrategy] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class KeyCase(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    CAMEL: ClassVar[KeyCase] = ...
    C: ClassVar[KeyCase] = ...
    PASCAL: ClassVar[KeyCase] = ...
    P: ClassVar[KeyCase] = ...
    KEBAB: ClassVar[KeyCase] = ...
    K: ClassVar[KeyCase] = ...
    SNAKE: ClassVar[KeyCase] = ...
    S: ClassVar[KeyCase] = ...
    AUTO: ClassVar[KeyCase] = ...
    A: ClassVar[KeyCase] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    def __call__(self, *args): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class DateTimeTo(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    ISO: ClassVar[DateTimeTo] = ...
    TIMESTAMP: ClassVar[DateTimeTo] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class EnvPrecedence(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    SECRETS_ENV_DOTENV: ClassVar[EnvPrecedence] = ...
    SECRETS_DOTENV_ENV: ClassVar[EnvPrecedence] = ...
    ENV_ONLY: ClassVar[EnvPrecedence] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...
